// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hilandyn_int_cpp
arma::vec hilandyn_int_cpp(arma::mat x, arma::mat nob, arma::uword nb, arma::uword nc, arma::uword ny, arma::uword nr, arma::uvec yrs, arma::uvec foc_ind, arma::uword cell_weights, arma::vec n_times_eBias_of_mad, arma::vec ev, arma::ivec cng_dir, double th_const, arma::uword noise_iter_max, arma::uword nob_init_min, arma::uword rmse, arma::uword use_last);
RcppExport SEXP _hilandyn_hilandyn_int_cpp(SEXP xSEXP, SEXP nobSEXP, SEXP nbSEXP, SEXP ncSEXP, SEXP nySEXP, SEXP nrSEXP, SEXP yrsSEXP, SEXP foc_indSEXP, SEXP cell_weightsSEXP, SEXP n_times_eBias_of_madSEXP, SEXP evSEXP, SEXP cng_dirSEXP, SEXP th_constSEXP, SEXP noise_iter_maxSEXP, SEXP nob_init_minSEXP, SEXP rmseSEXP, SEXP use_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nob(nobSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type ny(nySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type yrs(yrsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type foc_ind(foc_indSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type cell_weights(cell_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n_times_eBias_of_mad(n_times_eBias_of_madSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ev(evSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type cng_dir(cng_dirSEXP);
    Rcpp::traits::input_parameter< double >::type th_const(th_constSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type noise_iter_max(noise_iter_maxSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nob_init_min(nob_init_minSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type rmse(rmseSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type use_last(use_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(hilandyn_int_cpp(x, nob, nb, nc, ny, nr, yrs, foc_ind, cell_weights, n_times_eBias_of_mad, ev, cng_dir, th_const, noise_iter_max, nob_init_min, rmse, use_last));
    return rcpp_result_gen;
END_RCPP
}
// rle_cpp
arma::umat rle_cpp(arma::uvec x);
RcppExport SEXP _hilandyn_rle_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// mad_cpp
double mad_cpp(arma::vec x);
RcppExport SEXP _hilandyn_mad_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mad_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// sd_est_cpp
arma::vec sd_est_cpp(arma::mat x, arma::vec mad_bias);
RcppExport SEXP _hilandyn_sd_est_cpp(SEXP xSEXP, SEXP mad_biasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mad_bias(mad_biasSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_est_cpp(x, mad_bias));
    return rcpp_result_gen;
END_RCPP
}
// wgt_sam_cpp
arma::vec wgt_sam_cpp(arma::mat x, arma::uword nb, arma::uword nc);
RcppExport SEXP _hilandyn_wgt_sam_cpp(SEXP xSEXP, SEXP nbSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(wgt_sam_cpp(x, nb, nc));
    return rcpp_result_gen;
END_RCPP
}
// focal_values_cpp
arma::mat focal_values_cpp(arma::vec d, arma::uvec dim, arma::uword w);
RcppExport SEXP _hilandyn_focal_values_cpp(SEXP dSEXP, SEXP dimSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(focal_values_cpp(d, dim, w));
    return rcpp_result_gen;
END_RCPP
}
// rmse_cpp
arma::vec rmse_cpp(arma::mat x, arma::mat y, arma::uvec foc_ind);
RcppExport SEXP _hilandyn_rmse_cpp(SEXP xSEXP, SEXP ySEXP, SEXP foc_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type foc_ind(foc_indSEXP);
    rcpp_result_gen = Rcpp::wrap(rmse_cpp(x, y, foc_ind));
    return rcpp_result_gen;
END_RCPP
}
// cpt_cnd_cpp
arma::umat cpt_cnd_cpp(arma::mat x, arma::mat y, arma::mat nob, arma::uvec cpt, arma::uword nb, arma::uword nc, arma::uword nob_init_min);
RcppExport SEXP _hilandyn_cpt_cnd_cpp(SEXP xSEXP, SEXP ySEXP, SEXP nobSEXP, SEXP cptSEXP, SEXP nbSEXP, SEXP ncSEXP, SEXP nob_init_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nob(nobSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type cpt(cptSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nob_init_min(nob_init_minSEXP);
    rcpp_result_gen = Rcpp::wrap(cpt_cnd_cpp(x, y, nob, cpt, nb, nc, nob_init_min));
    return rcpp_result_gen;
END_RCPP
}
// proc_cpt_cpp
arma::mat proc_cpt_cpp(arma::mat x, arma::umat cptind, arma::umat chk_mat, arma::uvec cpt, arma::vec sd, arma::vec mad_bias, arma::vec wgts, arma::uword nc, arma::uword nb, double th_const);
RcppExport SEXP _hilandyn_proc_cpt_cpp(SEXP xSEXP, SEXP cptindSEXP, SEXP chk_matSEXP, SEXP cptSEXP, SEXP sdSEXP, SEXP mad_biasSEXP, SEXP wgtsSEXP, SEXP ncSEXP, SEXP nbSEXP, SEXP th_constSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type cptind(cptindSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type chk_mat(chk_matSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type cpt(cptSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mad_bias(mad_biasSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wgts(wgtsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type th_const(th_constSEXP);
    rcpp_result_gen = Rcpp::wrap(proc_cpt_cpp(x, cptind, chk_mat, cpt, sd, mad_bias, wgts, nc, nb, th_const));
    return rcpp_result_gen;
END_RCPP
}
// hd_bts_dcmp_cpp
Rcpp::List hd_bts_dcmp_cpp(arma::mat bts_coeffs, double p, arma::vec w);
RcppExport SEXP _hilandyn_hd_bts_dcmp_cpp(SEXP bts_coeffsSEXP, SEXP pSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type bts_coeffs(bts_coeffsSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(hd_bts_dcmp_cpp(bts_coeffs, p, w));
    return rcpp_result_gen;
END_RCPP
}
// hd_bts_dns_cpp
Rcpp::List hd_bts_dns_cpp(Rcpp::List bts_obj, arma::uword n, double lambda, double bal, arma::vec w, arma::uvec foc_ind);
RcppExport SEXP _hilandyn_hd_bts_dns_cpp(SEXP bts_objSEXP, SEXP nSEXP, SEXP lambdaSEXP, SEXP balSEXP, SEXP wSEXP, SEXP foc_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type bts_obj(bts_objSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type bal(balSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type foc_ind(foc_indSEXP);
    rcpp_result_gen = Rcpp::wrap(hd_bts_dns_cpp(bts_obj, n, lambda, bal, w, foc_ind));
    return rcpp_result_gen;
END_RCPP
}
// hd_bts_inv_cpp
Rcpp::List hd_bts_inv_cpp(Rcpp::List bts_obj, arma::uword n);
RcppExport SEXP _hilandyn_hd_bts_inv_cpp(SEXP bts_objSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type bts_obj(bts_objSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(hd_bts_inv_cpp(bts_obj, n));
    return rcpp_result_gen;
END_RCPP
}
// hd_bts_pp1_cpp
Rcpp::List hd_bts_pp1_cpp(Rcpp::List bts_obj, arma::uword n, double lambda);
RcppExport SEXP _hilandyn_hd_bts_pp1_cpp(SEXP bts_objSEXP, SEXP nSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type bts_obj(bts_objSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(hd_bts_pp1_cpp(bts_obj, n, lambda));
    return rcpp_result_gen;
END_RCPP
}
// hd_bts_cpt_cpp
Rcpp::List hd_bts_cpt_cpp(arma::mat x, arma::vec sd, arma::uword nb, double th_const, arma::vec weights, arma::uvec foc_ind);
RcppExport SEXP _hilandyn_hd_bts_cpt_cpp(SEXP xSEXP, SEXP sdSEXP, SEXP nbSEXP, SEXP th_constSEXP, SEXP weightsSEXP, SEXP foc_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type th_const(th_constSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type foc_ind(foc_indSEXP);
    rcpp_result_gen = Rcpp::wrap(hd_bts_cpt_cpp(x, sd, nb, th_const, weights, foc_ind));
    return rcpp_result_gen;
END_RCPP
}
// match_cpp
arma::vec match_cpp(arma::uvec a, arma::uvec b);
RcppExport SEXP _hilandyn_match_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(match_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// filter_bts_cpp
arma::vec filter_bts_cpp(arma::vec a);
RcppExport SEXP _hilandyn_filter_bts_cpp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_bts_cpp(a));
    return rcpp_result_gen;
END_RCPP
}
// orth_matrix_cpp
arma::mat orth_matrix_cpp(arma::rowvec d);
RcppExport SEXP _hilandyn_orth_matrix_cpp(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(orth_matrix_cpp(d));
    return rcpp_result_gen;
END_RCPP
}
// updating_cpp
arma::vec updating_cpp(arma::umat ee, arma::vec wgt_const, arma::vec wgt_lin, arma::rowvec bts_c, arma::uvec idx);
RcppExport SEXP _hilandyn_updating_cpp(SEXP eeSEXP, SEXP wgt_constSEXP, SEXP wgt_linSEXP, SEXP bts_cSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type ee(eeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wgt_const(wgt_constSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wgt_lin(wgt_linSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type bts_c(bts_cSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(updating_cpp(ee, wgt_const, wgt_lin, bts_c, idx));
    return rcpp_result_gen;
END_RCPP
}
// balance_np_cpp
arma::mat balance_np_cpp(arma::uvec paired, arma::umat ee, arma::uvec idx, arma::uword no_of_current_steps, arma::uword n);
RcppExport SEXP _hilandyn_balance_np_cpp(SEXP pairedSEXP, SEXP eeSEXP, SEXP idxSEXP, SEXP no_of_current_stepsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type paired(pairedSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type ee(eeSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type no_of_current_steps(no_of_current_stepsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(balance_np_cpp(paired, ee, idx, no_of_current_steps, n));
    return rcpp_result_gen;
END_RCPP
}
// balance_p_cpp
arma::mat balance_p_cpp(arma::umat pr, arma::umat ee_p1, arma::umat ee_p2, arma::uvec idx, arma::uword n);
RcppExport SEXP _hilandyn_balance_p_cpp(SEXP prSEXP, SEXP ee_p1SEXP, SEXP ee_p2SEXP, SEXP idxSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type pr(prSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type ee_p1(ee_p1SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type ee_p2(ee_p2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(balance_p_cpp(pr, ee_p1, ee_p2, idx, n));
    return rcpp_result_gen;
END_RCPP
}
// finding_cp_cpp
arma::uvec finding_cp_cpp(Rcpp::List bts_obj, arma::uword n);
RcppExport SEXP _hilandyn_finding_cp_cpp(SEXP bts_objSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type bts_obj(bts_objSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(finding_cp_cpp(bts_obj, n));
    return rcpp_result_gen;
END_RCPP
}
// L12_cpp
Rcpp::List L12_cpp(arma::uword l);
RcppExport SEXP _hilandyn_L12_cpp(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(L12_cpp(l));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hilandyn_hilandyn_int_cpp", (DL_FUNC) &_hilandyn_hilandyn_int_cpp, 17},
    {"_hilandyn_rle_cpp", (DL_FUNC) &_hilandyn_rle_cpp, 1},
    {"_hilandyn_mad_cpp", (DL_FUNC) &_hilandyn_mad_cpp, 1},
    {"_hilandyn_sd_est_cpp", (DL_FUNC) &_hilandyn_sd_est_cpp, 2},
    {"_hilandyn_wgt_sam_cpp", (DL_FUNC) &_hilandyn_wgt_sam_cpp, 3},
    {"_hilandyn_focal_values_cpp", (DL_FUNC) &_hilandyn_focal_values_cpp, 3},
    {"_hilandyn_rmse_cpp", (DL_FUNC) &_hilandyn_rmse_cpp, 3},
    {"_hilandyn_cpt_cnd_cpp", (DL_FUNC) &_hilandyn_cpt_cnd_cpp, 7},
    {"_hilandyn_proc_cpt_cpp", (DL_FUNC) &_hilandyn_proc_cpt_cpp, 10},
    {"_hilandyn_hd_bts_dcmp_cpp", (DL_FUNC) &_hilandyn_hd_bts_dcmp_cpp, 3},
    {"_hilandyn_hd_bts_dns_cpp", (DL_FUNC) &_hilandyn_hd_bts_dns_cpp, 6},
    {"_hilandyn_hd_bts_inv_cpp", (DL_FUNC) &_hilandyn_hd_bts_inv_cpp, 2},
    {"_hilandyn_hd_bts_pp1_cpp", (DL_FUNC) &_hilandyn_hd_bts_pp1_cpp, 3},
    {"_hilandyn_hd_bts_cpt_cpp", (DL_FUNC) &_hilandyn_hd_bts_cpt_cpp, 6},
    {"_hilandyn_match_cpp", (DL_FUNC) &_hilandyn_match_cpp, 2},
    {"_hilandyn_filter_bts_cpp", (DL_FUNC) &_hilandyn_filter_bts_cpp, 1},
    {"_hilandyn_orth_matrix_cpp", (DL_FUNC) &_hilandyn_orth_matrix_cpp, 1},
    {"_hilandyn_updating_cpp", (DL_FUNC) &_hilandyn_updating_cpp, 5},
    {"_hilandyn_balance_np_cpp", (DL_FUNC) &_hilandyn_balance_np_cpp, 5},
    {"_hilandyn_balance_p_cpp", (DL_FUNC) &_hilandyn_balance_p_cpp, 5},
    {"_hilandyn_finding_cp_cpp", (DL_FUNC) &_hilandyn_finding_cp_cpp, 2},
    {"_hilandyn_L12_cpp", (DL_FUNC) &_hilandyn_L12_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_hilandyn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
