# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rle_cpp <- function(x) {
    .Call('_hilandyn_rle_cpp', PACKAGE = 'hilandyn', x)
}

mad_cpp <- function(x) {
    .Call('_hilandyn_mad_cpp', PACKAGE = 'hilandyn', x)
}

sd_est_cpp <- function(x, mad_bias) {
    .Call('_hilandyn_sd_est_cpp', PACKAGE = 'hilandyn', x, mad_bias)
}

wgt_sam_cpp <- function(x, nb, nc) {
    .Call('_hilandyn_wgt_sam_cpp', PACKAGE = 'hilandyn', x, nb, nc)
}

focal_values_cpp <- function(d, dim, w) {
    .Call('_hilandyn_focal_values_cpp', PACKAGE = 'hilandyn', d, dim, w)
}

rmse_cpp <- function(x, y, foc_ind) {
    .Call('_hilandyn_rmse_cpp', PACKAGE = 'hilandyn', x, y, foc_ind)
}

cpt_cnd_cpp <- function(x, y, nob, cpt, nb, nc, nob_init_min) {
    .Call('_hilandyn_cpt_cnd_cpp', PACKAGE = 'hilandyn', x, y, nob, cpt, nb, nc, nob_init_min)
}

proc_cpt_cpp <- function(x, cptind, chk_mat, cpt, sd, mad_bias, wgts, nc, nb, th_const) {
    .Call('_hilandyn_proc_cpt_cpp', PACKAGE = 'hilandyn', x, cptind, chk_mat, cpt, sd, mad_bias, wgts, nc, nb, th_const)
}

hd_bts_dcmp_cpp <- function(bts_coeffs, p, w) {
    .Call('_hilandyn_hd_bts_dcmp_cpp', PACKAGE = 'hilandyn', bts_coeffs, p, w)
}

hd_bts_dns_cpp <- function(bts_obj, lambda, bal, w, foc_ind) {
    .Call('_hilandyn_hd_bts_dns_cpp', PACKAGE = 'hilandyn', bts_obj, lambda, bal, w, foc_ind)
}

hd_bts_inv_cpp <- function(bts_obj) {
    .Call('_hilandyn_hd_bts_inv_cpp', PACKAGE = 'hilandyn', bts_obj)
}

hd_bts_pp1_cpp <- function(bts_obj, lambda) {
    .Call('_hilandyn_hd_bts_pp1_cpp', PACKAGE = 'hilandyn', bts_obj, lambda)
}

hd_bts_cpt_cpp <- function(x, sd, nb, th_const, weights, foc_ind) {
    .Call('_hilandyn_hd_bts_cpt_cpp', PACKAGE = 'hilandyn', x, sd, nb, th_const, weights, foc_ind)
}

match_cpp <- function(a, b) {
    .Call('_hilandyn_match_cpp', PACKAGE = 'hilandyn', a, b)
}

filter_bts_cpp <- function(a) {
    .Call('_hilandyn_filter_bts_cpp', PACKAGE = 'hilandyn', a)
}

orth_matrix_cpp <- function(d) {
    .Call('_hilandyn_orth_matrix_cpp', PACKAGE = 'hilandyn', d)
}

updating_cpp <- function(ee, wgt_const, wgt_lin, bts_c, idx) {
    .Call('_hilandyn_updating_cpp', PACKAGE = 'hilandyn', ee, wgt_const, wgt_lin, bts_c, idx)
}

balance_np_cpp <- function(paired, ee, idx, no_of_current_steps, n) {
    .Call('_hilandyn_balance_np_cpp', PACKAGE = 'hilandyn', paired, ee, idx, no_of_current_steps, n)
}

balance_p_cpp <- function(pr, ee_p1, ee_p2, idx, n) {
    .Call('_hilandyn_balance_p_cpp', PACKAGE = 'hilandyn', pr, ee_p1, ee_p2, idx, n)
}

finding_cp_cpp <- function(bts_obj) {
    .Call('_hilandyn_finding_cp_cpp', PACKAGE = 'hilandyn', bts_obj)
}

L12_cpp <- function(l) {
    .Call('_hilandyn_L12_cpp', PACKAGE = 'hilandyn', l)
}

